project:
  type: book

book:
  title: Tragverhalten von Stahlbetontragwerken
  subtitle: Ansätze zur Verformungsberechnung
  author: Pascal Gitz
  date: 2024.01.19
  date-format: full
  chapters:
    - index.qmd
    - 04_Theorie.qmd
    - 06_Versuch_2_A3_Jaeger.ipynb
    - 07_Versuch_SV_14.ipynb
    - 98_summary.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  pdf:
    pdf-engine: latexmk
  # Titelblatt und Kurzfassung
    template-partials:
      - title.tex
    include-in-header: 
      - file: styling_nach_hslu.sty
    include-before-body:
      - file: 01_redlichkeitserklaerung.tex
      - file: 02_kurzfassung.tex


  # Dokument
    documentclass: scrreprt
    toc-depth: 2
    lof: true
    lot: true
    lang: de
    keep-tex: true

  # Figuren
    fig-pos: 'H'
    fig-format: svg
  
  # Verlinkungen
    csl: diabetologia.csl
    link-citations: True
    linkcolor: Black
  
  # Tabellen
    tbl-colwidths: [50,50]
    
  # Code
    execute:
      echo: false
      warning: false
  
  # Font
    mainfont: Palatino Linotype
    fontsize: 12pt
    classoption: egregdoesnotlikesansseriftitles


  # docx:
  #   lang: de
  #   fig-format: svg
  #   csl: diabetologia.csl
  #   link-citations: true
  #   tbl-colwidths: [50,50]
  #   echo: false
  #   warning: false



  # html:
  #   fig-format: svg
  #   lang: de
  #   csl: diabetologia.csl
  #   link-citations: True
  #   tbl-colwidths: [50,50]

